/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainFrame;

import G2D.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class FrameBendaDuaD extends javax.swing.JInternalFrame {

    /**
     * Creates new form Geometry2D
     */
    public FrameBendaDuaD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        sisi1 = new javax.swing.JLabel();
        sisi2 = new javax.swing.JLabel();
        inputComboBoxJenis = new javax.swing.JComboBox<>();
        sisi3 = new javax.swing.JLabel();
        prosesButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        inputSatu = new javax.swing.JTextField();
        inputDua = new javax.swing.JTextField();
        inputTiga = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        outputHasil = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        outputHasil2 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("2 Dimensi");
        setPreferredSize(new java.awt.Dimension(650, 397));
        setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Benda 2 Dimensi");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Jenis ");

        sisi1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sisi1.setText("-");

        sisi2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sisi2.setText("-");

        inputComboBoxJenis.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        inputComboBoxJenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis", "Belah ketupat", "Jajar genjang", "Layang-layang", "Lingkaran", "Persegi", "Persegi Panjang", "Segitiga", "Trapesium" }));
        inputComboBoxJenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputComboBoxJenisActionPerformed(evt);
            }
        });

        sisi3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sisi3.setText("-");

        prosesButton.setText("Proses");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        inputSatu.setEnabled(false);
        inputSatu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputSatuActionPerformed(evt);
            }
        });

        inputDua.setEnabled(false);

        inputTiga.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Luas");

        outputHasil.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Keliling");

        outputHasil2.setEditable(false);
        outputHasil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputHasil2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(prosesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(sisi1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputSatu))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sisi3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputTiga))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(sisi2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(inputDua, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(outputHasil, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                    .addComponent(outputHasil2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputComboBoxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(inputComboBoxJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sisi1)
                    .addComponent(inputSatu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sisi2)
                    .addComponent(inputDua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sisi3)
                    .addComponent(inputTiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(outputHasil2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(prosesButton)
                    .addComponent(outputHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        inputComboBoxJenis.getAccessibleContext().setAccessibleName("Benda 2 D");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        double nilaiSatu, nilaiDua, nilaiTiga, Hasil, Hasil2;
        try {
        switch (inputComboBoxJenis.getSelectedIndex()) {
            case 1:
                nilaiSatu = Double.parseDouble(inputSatu.getText());
                nilaiDua = Double.parseDouble(inputDua.getText());
                Belahketupat belahketupat = new Belahketupat(nilaiSatu, nilaiDua);
                Hasil = belahketupat.hitungLuas();
                Hasil2 = belahketupat.hitungKeliling();
                outputHasil.setText("" + Hasil);
                outputHasil2.setText("" + Hasil2);
                break;
            case 2:
                nilaiSatu = Double.parseDouble(inputSatu.getText());
                nilaiDua = Double.parseDouble(inputDua.getText());
                Jajargenjang jajargenjang = new Jajargenjang(nilaiSatu, nilaiDua);
                Hasil = jajargenjang.hitungLuas();
                Hasil2 = jajargenjang.hitungKeliling();
                int JajarGenjangForLife = (int) Hasil2;
                outputHasil.setText("" + Hasil);
                outputHasil2.setText("" + JajarGenjangForLife);
                break;
            case 3:
                nilaiSatu = Double.parseDouble(inputSatu.getText());
                nilaiDua = Double.parseDouble(inputDua.getText());
                Layang2 layangLayang = new Layang2(nilaiSatu, nilaiDua);
                Hasil = layangLayang.hitungLuas();
                Hasil2 = layangLayang.hitungKeliling();
                outputHasil.setText("" + Hasil);
                outputHasil2.setText("" + Hasil2);
                break;
            case 4:
                nilaiSatu = Double.parseDouble(inputSatu.getText());
                Lingkaran lingkaran = new Lingkaran(nilaiSatu);
                Hasil = lingkaran.hitungLuas();
                Hasil2 = lingkaran.hitungKeliling();
                outputHasil.setText("" + Hasil);
                outputHasil2.setText("" + Hasil2);
                break;
            case 5:
                nilaiSatu = Double.parseDouble(inputSatu.getText());
                Persegi persegi = new Persegi(nilaiSatu);
                Hasil = persegi.hitungLuas();
                Hasil2 = persegi.hitungKeliling();
                outputHasil.setText("" + Hasil);
                outputHasil2.setText("" + Hasil2);
                break;
            case 6:
                nilaiSatu = Double.parseDouble(inputSatu.getText());
                nilaiDua = Double.parseDouble(inputDua.getText());
                Persegipanjang persegiPanjang = new Persegipanjang(nilaiSatu, nilaiDua);
                Hasil = persegiPanjang.hitungLuas();
                Hasil2 = persegiPanjang.hitungKeliling();
                outputHasil.setText("" + Hasil);
                outputHasil2.setText("" + Hasil2);
                break;
            case 7:
                nilaiSatu = Double.parseDouble(inputSatu.getText());
                nilaiDua = Double.parseDouble(inputDua.getText());
                Segitiga segitiga = new Segitiga(nilaiSatu, nilaiDua);
                Hasil = segitiga.hitungLuas();
                Hasil2 = segitiga.hitungKeliling();
                outputHasil.setText("" + Hasil);
                outputHasil2.setText("" + Hasil2);
                break;
            case 8:
                nilaiSatu = Double.parseDouble(inputSatu.getText());
                nilaiDua = Double.parseDouble(inputDua.getText());
                nilaiTiga = Double.parseDouble(inputTiga.getText());
                Trapesium trapesium = new Trapesium(nilaiSatu, nilaiDua, nilaiTiga);
                Hasil = trapesium.hitungLuas();
                Hasil2 = trapesium.hitungKeliling();
                outputHasil.setText("" + Hasil);
                outputHasil2.setText("" + Hasil2);
                break;
            }
        } catch (NumberFormatException e) {
            // Menangani kesalahan saat input bukan angka
            JOptionPane.showMessageDialog(null, "Masukkan harus berupa angka.");
        }

    }//GEN-LAST:event_prosesButtonActionPerformed

    private void inputSatuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputSatuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputSatuActionPerformed

    private void inputComboBoxJenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputComboBoxJenisActionPerformed
        switch (inputComboBoxJenis.getSelectedIndex()) {
            case 0:
                inputTiga.setEnabled(false);
                inputSatu.setEnabled(false);
                inputDua.setEnabled(false);
                sisi1.setText("-");
                sisi2.setText("-");
                sisi3.setText("-");
                inputTiga.setText("");
                inputSatu.setText("");
                inputDua.setText("");
                outputHasil.setText("");
                outputHasil2.setText("");
                break;
            case 1: //Belahketupat
                inputTiga.setEnabled(false);
                inputSatu.setEnabled(true);
                inputDua.setEnabled(true);
                sisi1.setText("Diagonal 1");
                sisi2.setText("Diagonal 2");
                sisi3.setText("-");
                inputTiga.setText("");
                inputSatu.setText("");
                inputDua.setText("");
                outputHasil.setText("");
                outputHasil2.setText("");
                break;
            case 2: //Jajargenjang
                inputTiga.setEnabled(false);
                inputSatu.setEnabled(true);
                inputDua.setEnabled(true);
                sisi1.setText("Alas");
                sisi2.setText("Tinggi");
                sisi3.setText("-");
                inputTiga.setText("");
                inputSatu.setText("");
                inputDua.setText("");
                outputHasil.setText("");
                outputHasil2.setText("");
                break;
            case 3: // Layang2
                inputTiga.setEnabled(false);
                inputSatu.setEnabled(true);
                inputDua.setEnabled(true);
                sisi1.setText("Diagonal 1");
                sisi2.setText("Diagonal 2");
                sisi3.setText("-");
                inputTiga.setText("");
                inputSatu.setText("");
                inputDua.setText("");
                outputHasil.setText("");
                outputHasil2.setText("");
                break;
            case 4: // Lingkaran
                inputTiga.setEnabled(false);
                inputSatu.setEnabled(true);
                inputDua.setEnabled(false);
                sisi1.setText("Jari2");
                sisi2.setText("-");
                sisi3.setText("-");
                inputTiga.setText("");
                inputSatu.setText("");
                inputDua.setText("");
                outputHasil.setText("");
                outputHasil2.setText("");
                break;
            case 5: // Persegi
                inputTiga.setEnabled(false);
                inputSatu.setEnabled(true);
                inputDua.setEnabled(false);
                sisi1.setText("Sisi");
                sisi2.setText("-");
                sisi3.setText("-");
                inputTiga.setText("");
                inputSatu.setText("");
                inputDua.setText("");
                outputHasil.setText("");
                outputHasil2.setText("");
                break;
            case 6: // Persegi Panjang
                inputTiga.setEnabled(false);
                inputSatu.setEnabled(true);
                inputDua.setEnabled(true);
                sisi1.setText("Panjang");
                sisi2.setText("Lebar");
                sisi3.setText("-");
                inputTiga.setText("");
                inputSatu.setText("");
                inputDua.setText("");
                outputHasil.setText("");
                outputHasil2.setText("");
                break;
            case 7: // Segitiga
                inputTiga.setEnabled(false);
                inputSatu.setEnabled(true);
                inputDua.setEnabled(true);
                sisi1.setText("Alas");
                sisi2.setText("Panjang");
                sisi3.setText("-");
                inputTiga.setText("");
                inputSatu.setText("");
                inputDua.setText("");
                outputHasil.setText("");
                outputHasil2.setText("");
                break;
            case 8: // Trapesium
                inputTiga.setEnabled(true);
                inputSatu.setEnabled(true);
                inputDua.setEnabled(true);
                sisi1.setText("Sisi 1");
                sisi2.setText("Sisi 2");
                sisi3.setText("Tinggi");
                inputTiga.setText("");
                inputSatu.setText("");
                inputDua.setText("");
                outputHasil.setText("");
                outputHasil2.setText("");
                break;

        }
    }//GEN-LAST:event_inputComboBoxJenisActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        inputTiga.setText("");
        inputSatu.setText("");
        inputDua.setText("");
        outputHasil.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void outputHasil2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputHasil2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outputHasil2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> inputComboBoxJenis;
    private javax.swing.JTextField inputDua;
    private javax.swing.JTextField inputSatu;
    private javax.swing.JTextField inputTiga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField outputHasil;
    private javax.swing.JTextField outputHasil2;
    private javax.swing.JButton prosesButton;
    private javax.swing.JLabel sisi1;
    private javax.swing.JLabel sisi2;
    private javax.swing.JLabel sisi3;
    // End of variables declaration//GEN-END:variables

}
