/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.yogdev.bioskop.view;


import id.yogdev.bioskop.controller.FilmController;
import id.yogdev.bioskop.model.CrudState;
import id.yogdev.bioskop.model.Film;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import id.yogdev.bioskop.database.KoneksiDatabase;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JFrame;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.plaf.basic.BasicInternalFrameTitlePane;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;

/**
 *
 * @author Asus X450J
 */
public class FilmFrame extends javax.swing.JFrame implements Observer{

    private FilmController filmController = new FilmController();

    Connection con;
    
    /**
     * Creates new form ListFilmFrame
     */
    public FilmFrame() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        filmController.addObserver(this);
        setFilmTable(filmController.getAllFilm());
        
        if (!KoneksiDatabase.isConnect()){
            System.exit(0);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namafilmTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        genreComboBox = new javax.swing.JComboBox<>();
        simpanfilmButton = new javax.swing.JButton();
        batalsimpanfilmButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jammulai1 = new javax.swing.JComboBox<>();
        jamselesai1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jammulai2 = new javax.swing.JComboBox<>();
        jamselesai2 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jammulai3 = new javax.swing.JComboBox<>();
        jamselesai3 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        ruangComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        film_table = new javax.swing.JTable();
        resetButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        hapusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("INPUT FILM");

        jLabel2.setText("Nama Film:");

        namafilmTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namafilmTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Genre:");

        genreComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "Animasi", "Dokumenter", "Drama", "Fantasi", "Horror", "Komedi", "Kriminal", "Laga", "Petualangan", " ", " " }));
        genreComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreComboBoxActionPerformed(evt);
            }
        });

        simpanfilmButton.setText("SIMPAN");
        simpanfilmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanfilmButtonActionPerformed(evt);
            }
        });

        batalsimpanfilmButton.setText("KEMBALI");
        batalsimpanfilmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalsimpanfilmButtonActionPerformed(evt);
            }
        });

        jLabel4.setText("Jam Mulai ke-1:");

        jammulai1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "09:00", "10:15", "11:30", "12:45", "13:00", "14:15", "15:30", "16:45", "17:00", "18:15", "19:30", "20:45", "21:00", " " }));

        jamselesai1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "09:00", "10:15", "11:30", "12:45", "13:00", "14:15", "15:30", "16:45", "17:00", "18:15", "19:30", "20:45", "21:00", " " }));

        jLabel5.setText("Jam Mulai ke-2:");

        jammulai2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "09:00", "10:15", "11:30", "12:45", "13:00", "14:15", "15:30", "16:45", "17:00", "18:15", "19:30", "20:45", "21:00", " " }));
        jammulai2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jammulai2ActionPerformed(evt);
            }
        });

        jamselesai2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "09:00", "10:15", "11:30", "12:45", "13:00", "14:15", "15:30", "16:45", "17:00", "18:15", "19:30", "20:45", "21:00", " " }));

        jLabel6.setText("Jam Mulai ke-3:");

        jammulai3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "09:00", "10:15", "11:30", "12:45", "13:00", "14:15", "15:30", "16:45", "17:00", "18:15", "19:30", "20:45", "21:00", " " }));

        jamselesai3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "09:00", "10:15", "11:30", "12:45", "13:00", "14:15", "15:30", "16:45", "17:00", "18:15", "19:30", "20:45", "21:00", " " }));

        jLabel7.setText("Ruang:");

        ruangComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "A", "B", "C", "D", "E" }));

        jLabel8.setText("Jam Selesai ke-1:");

        jLabel9.setText("Jam Selesai ke-2:");

        jLabel10.setText("Jam Selesai ke-3:");

        film_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        jScrollPane2.setViewportView(film_table);

        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("DAFTAR FILM");

        hapusButton.setText("HAPUS");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel2))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namafilmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ruangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jammulai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jammulai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jammulai3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jamselesai3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jamselesai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jamselesai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(batalsimpanfilmButton))
                                .addGap(17, 17, 17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel1)))
                                    .addComponent(simpanfilmButton))
                                .addGap(1, 1, 1)
                                .addComponent(hapusButton)
                                .addGap(35, 35, 35)
                                .addComponent(resetButton)))
                        .addGap(264, 264, 264))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namafilmTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(genreComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jammulai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jamselesai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jammulai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jamselesai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jammulai3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jamselesai3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ruangComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanfilmButton)
                    .addComponent(batalsimpanfilmButton)
                    .addComponent(resetButton)
                    .addComponent(hapusButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void namafilmTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namafilmTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namafilmTextFieldActionPerformed

    private void simpanfilmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanfilmButtonActionPerformed
        // TODO add your handling code here:
        String name = namafilmTextField.getText();
        String genre = (String) genreComboBox.getSelectedItem();
        String jam_mulai_pertama = (String) jammulai1.getSelectedItem();
        String jam_selesai_pertama = (String) jamselesai1.getSelectedItem();
        String jam_mulai_kedua = (String) jammulai2.getSelectedItem();
        String jam_selesai_kedua = (String) jamselesai2.getSelectedItem();
        String jam_mulai_ketiga = (String) jammulai3.getSelectedItem();
        String jam_selesai_ketiga = (String) jamselesai3.getSelectedItem();
        String ruang = (String) ruangComboBox.getSelectedItem();
        
        Film f = new Film(null, name, genre, jam_mulai_pertama, jam_selesai_pertama, jam_mulai_kedua, jam_selesai_kedua, jam_mulai_ketiga, jam_selesai_ketiga, ruang);        
        filmController.manipulate(f,CrudState.INSERT);
    }//GEN-LAST:event_simpanfilmButtonActionPerformed

    @Override
    public void update(Observable o, Object arg) {
        if (o==filmController){
            if (arg==null){
                JOptionPane.showMessageDialog(this, "Produk gagal diperbaharui karena kegagalan koneksi ke database");
            }else{            
                Film f = (Film) arg;
                if (filmController.getCrudState() == CrudState.INSERT){
                    JOptionPane.showMessageDialog(this, f.getName()+" berhasil ditambahkan");
                }
                setFilmTable(filmController.getAllFilm());
                resetForm(); 
            }            
        }
    }
    
    public void resetForm() {
        namafilmTextField.setText("");
        genreComboBox.setSelectedItem("-------");
        jammulai1.setSelectedItem("-------");
        jamselesai1.setSelectedItem("-------");
        jammulai2.setSelectedItem("-------");
        jamselesai2.setSelectedItem("-------");
        jammulai3.setSelectedItem("-------");
        jamselesai3.setSelectedItem("-------");
        ruangComboBox.setSelectedItem("-------");
    }
    
    
    private void setFilmTable(List<Film> listFilm) {
        if (listFilm==null){
            JOptionPane.showMessageDialog(this, "Data film gagal diambil dari database","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }else{
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(
                new String[] {
                    "Nama Film",
                    "Genre",
                    "Jam Mulai ke-1",
                    "Jam Selesai ke-1",
                    "Jam Mulai ke-2",
                    "Jam Selesai ke-2",
                    "Jam Mulai ke-3",
                    "Jam Selesai ke-3",
                    "Ruang"
                }
            );
            
            for (Film f : listFilm) {
                Object[] o = new Object[10];
                o[0] = f.getName();
                o[1] = f.getGenre();
                o[2] = f.getJamMulai1();
                o[3] = f.getJamSelesai1();
                o[4] = f.getJamMulai2();
                o[5] = f.getJamSelesai2();
                o[6] = f.getJamMulai3();
                o[7] = f.getJamSelesai3();
                o[8] = f.getRuang();
                tableModel.addRow(o);
            }
            film_table.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
            film_table.setModel(tableModel);
            film_table.getColumnModel().getColumn(0).setMinWidth(120);
            film_table.getColumnModel().getColumn(2).setMaxWidth(50);
        }
    }
        
                    
    private void genreComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreComboBoxActionPerformed

    private void jammulai2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jammulai2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jammulai2ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_hapusButtonActionPerformed

    private void batalsimpanfilmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalsimpanfilmButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_batalsimpanfilmButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilmFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batalsimpanfilmButton;
    private javax.swing.JTable film_table;
    private javax.swing.JComboBox<String> genreComboBox;
    private javax.swing.JButton hapusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> jammulai1;
    private javax.swing.JComboBox<String> jammulai2;
    private javax.swing.JComboBox<String> jammulai3;
    private javax.swing.JComboBox<String> jamselesai1;
    private javax.swing.JComboBox<String> jamselesai2;
    private javax.swing.JComboBox<String> jamselesai3;
    private javax.swing.JTextField namafilmTextField;
    private javax.swing.JButton resetButton;
    private javax.swing.JComboBox<String> ruangComboBox;
    private javax.swing.JButton simpanfilmButton;
    // End of variables declaration//GEN-END:variables
}
