/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.yogdev.bioskop.view;

import java.sql.Connection;
import id.yogdev.bioskop.database.KoneksiDatabase;
import id.yogdev.bioskop.model.Transaksi;
import id.yogdev.bioskop.model.Film;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import id.yogdev.bioskop.controller.FilmController;
import java.text.SimpleDateFormat;
import java.sql.Statement;
import id.yogdev.bioskop.controller.TransaksiController;
import id.yogdev.bioskop.model.CrudState;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author Asus X450J
 */
public class TicketDataFrame extends javax.swing.JFrame implements Observer {
    String tanggal;
    KoneksiDatabase koneksiDatabase = new KoneksiDatabase();
    private final FilmController fController= new FilmController();
    private final TransaksiController transaksiController = new TransaksiController();

    
  
    /**
     * Creates new form TicketDataFrame
     */
    public TicketDataFrame() {
        initComponents();
        setFilm(fController.getAllFilm());
        transaksiController.addObserver(this);
        setTransaksiTable(transaksiController.getAllTransaksi());
        
        if (!KoneksiDatabase.isConnect()){
            System.exit(0);
        }
 
    }
    
    private void setFilm(List<Film> Film) {
        if(Film==null){
        JOptionPane.showMessageDialog(this,"Data Kelas GAGAL Di AKSES","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }
        else{
        filmComboBox.setModel(new DefaultComboBoxModel(Film.toArray()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        prosesButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        filmComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        kursiComboBox = new javax.swing.JComboBox<>();
        resetButton = new javax.swing.JButton();
        batalButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        barisanComboBox = new javax.swing.JComboBox<>();
        Showtxt = new javax.swing.JLabel();
        showComboBox = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        transaksi_Table = new javax.swing.JTable();
        kelasComboBox = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        hargaTextField = new javax.swing.JTextField();
        jumlahText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        simpanTransaksiButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        prosesButton.setText("PROSES");
        prosesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesButtonActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Film:");

        filmComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filmComboBoxActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Kursi:");

        kursiComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30" }));
        kursiComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kursiComboBoxActionPerformed(evt);
            }
        });

        resetButton.setText("RESET");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        batalButton.setText("KEMBALI");
        batalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalButtonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Barisan:");

        barisanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "A", "B", "C", "D", "E" }));

        Showtxt.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Showtxt.setText("Show ");

        showComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-------", "1", "2", "3", "4", "5" }));
        showComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showComboBoxActionPerformed(evt);
            }
        });

        transaksi_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane5.setViewportView(transaksi_Table);

        kelasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reguler", "VIP" }));
        kelasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelasComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("Kelas");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah:");

        jumlahText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahTextActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Total Harga:");

        simpanTransaksiButton.setText("SIMPAN");
        simpanTransaksiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanTransaksiButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel6.setText("INPUT TRANSAKSI");

        jLabel8.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel8.setText("DAFTAR TRANSAKSI");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(Showtxt))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(showComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jumlahText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(barisanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kursiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(182, 182, 182))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(simpanTransaksiButton)
                        .addGap(35, 35, 35)
                        .addComponent(batalButton)
                        .addGap(39, 39, 39)
                        .addComponent(resetButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(324, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(322, 322, 322)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Showtxt)
                            .addComponent(showComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(filmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(barisanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jumlahText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(batalButton)
                            .addComponent(resetButton)
                            .addComponent(simpanTransaksiButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jLabel6)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kursiComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kelasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(383, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addGap(136, 136, 136)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void kursiComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kursiComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kursiComboBoxActionPerformed

    private void batalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        new MainFrame().setVisible(true);
    }//GEN-LAST:event_batalButtonActionPerformed

    private void filmComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filmComboBoxActionPerformed

    }//GEN-LAST:event_filmComboBoxActionPerformed

    private void showComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showComboBoxActionPerformed

    private void prosesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prosesButtonActionPerformed

    private void kelasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelasComboBoxActionPerformed
        // TODO add your handling code here:
        String kelas = kelasComboBox.getSelectedItem().toString();
        int h, hasil;
        if (kelas.equals("Reguler")){
            h=50000;
        }
        else if(kelas.equals("VIP")){
            h=100000;
        }
        else{
            h=0;
        }
        int a = Integer.parseInt(jumlahText.getText());
        hasil=a*h;
        hargaTextField.setText(""+ hasil);
    }//GEN-LAST:event_kelasComboBoxActionPerformed

    private void simpanTransaksiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanTransaksiButtonActionPerformed
        // TODO add your handling code here:
        String show = (String) showComboBox.getSelectedItem();
        Film film =(Film) filmComboBox.getSelectedItem();
        String barisan = (String) barisanComboBox.getSelectedItem();
        String jumlah = (String) jumlahText.getText();
        String kursi = (String) kursiComboBox.getSelectedItem();
        String kelas = (String) kelasComboBox.getSelectedItem();
        int harga= Integer.parseInt(hargaTextField.getText());
        
        Transaksi t = new Transaksi(null, film, show, barisan, jumlah, kursi, kelas, harga);        
        transaksiController.manipulate(t,CrudState.INSERT);
    }//GEN-LAST:event_simpanTransaksiButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        resetForm();
    }//GEN-LAST:event_resetButtonActionPerformed

    private void jumlahTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahTextActionPerformed

    @Override
    public void update(Observable o, Object arg) {
        if (o==transaksiController){
            if (arg==null){
                JOptionPane.showMessageDialog(this, "Produk gagal diperbaharui karena kegagalan koneksi ke database");
            }else{            
                Transaksi t = (Transaksi) arg;
                if (transaksiController.getCrudState() == CrudState.INSERT){
                    JOptionPane.showMessageDialog(this, t.getFilm()+" berhasil ditambahkan");
                }
                setTransaksiTable(transaksiController.getAllTransaksi());
                resetForm(); 
            }            
        }
    }
    
    public void resetForm() {
        showComboBox.setSelectedItem("-------");
        filmComboBox.setSelectedItem("-------");
        barisanComboBox.setSelectedItem("-------");
        jumlahText.setText("");
        kursiComboBox.setSelectedItem("-------");
        kelasComboBox.setSelectedItem("-------");
        hargaTextField.setText("");
      
    }
    
     private void setTransaksiTable(List<Transaksi> listTransaksi) {
        if (listTransaksi==null){
            JOptionPane.showMessageDialog(this, "Data film gagal diambil dari database","DATABASE FAILED",JOptionPane.ERROR_MESSAGE);
        }else{
            DefaultTableModel tableModel = new DefaultTableModel();
            tableModel.setColumnIdentifiers(
                new String[] {
                    "Film",
                    "Show",
                    "Barisan",
                    "Kelas",
                    "Kursi",
                    "Jumlah",
                    "Total Harga",
                }
            );
            
            for (Transaksi t : listTransaksi) {
                Object[] o = new Object[7];
                o[0] = t.getFilm();
                o[1] = t.getShow();
                o[2] = t.getBarisan();
                o[3] = t.getKelas();
                o[4] = t.getKursi();
                o[5] = t.getJumlah();
                o[6] = t.getHarga();
                tableModel.addRow(o);
            }
            transaksi_Table.setAutoResizeMode( javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS );
            transaksi_Table.setModel(tableModel);
            transaksi_Table.getColumnModel().getColumn(0).setMinWidth(120);
            transaksi_Table.getColumnModel().getColumn(2).setMaxWidth(50);
        }
    }
    
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicketDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicketDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicketDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicketDataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TicketDataFrame().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Showtxt;
    private javax.swing.JComboBox<String> barisanComboBox;
    private javax.swing.JButton batalButton;
    private javax.swing.JComboBox<String> filmComboBox;
    private javax.swing.JTextField hargaTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jumlahText;
    private javax.swing.JComboBox<String> kelasComboBox;
    private javax.swing.JComboBox<String> kursiComboBox;
    private javax.swing.JButton prosesButton;
    private javax.swing.JButton resetButton;
    private javax.swing.JComboBox<String> showComboBox;
    private javax.swing.JButton simpanTransaksiButton;
    private javax.swing.JTable transaksi_Table;
    // End of variables declaration//GEN-END:variables

    
}
